### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by un-lock-me** [gauravshelangia/KerasModel_Android#1]
I wish It had a file to say that for another keras model to be used in android what kind of changing should be applied to the code,

if you prepare such a document It would be best, because I couldnt find a good source in the net, so when I found your code I was supper happy.

Also I didnt get whats the Importiris for?

**Comment by gauravshelangia** [comment]
Importiris is just a sample code. And by the time, I will write a **gist** explaining how to import keras model on android.
